#!/bin/sh

# Restore wallpaper
bash $HOME/.config/feh/fehbg

# Launch polybar
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

# Define window styles
bspc config border_width 4
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "#7e9cd8"
bspc config normal_border_color "#54546d"
bspc config active_border_color "#98bb6c"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# Fix pointer
xsetroot -cursor_name left_ptr

# Define workspaces
workspaces() {
  name=1
  for monitor in `bspc query -M`; do
    bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '懶' '' '漣'
    let name++
  done
}
workspaces

## Workspace 1 (Terminals)
declare -a terminals=(Alacritty)
for i in ${terminals[@]}; do
  bspc rule -a $i desktop='^1' follow=on focus=on;
done

## Workspace 2 (Web Browsers)
declare -a web=(firefox Chromium)
for i in ${web[@]}; do
  bspc rule -a $i desktop='^2' follow=on focus=on;
done

## Workspace 3 (Files)
declare -a files=(Gftp-gtk Thunar Deluge)
for i in ${files[@]}; do
  bspc rule -a $i desktop='^3' follow=on focus=on;
done

## Workspace 4 (Documents)
declare -a documents=(Zathura)
for i in ${documents[@]}; do
  bspc rule -a $i desktop='^4' follow=on focus=on state=tiled;
done

# Workspace 5 (Code Editor)
declare -a code=(code-oss)
for i in ${code[@]}; do
  bspc rule -a $i desktop='^5' follow=on focus=on;
done

## Workspace 6 (Media)
declare -a media=(Gimp mpv)
for i in ${media[@]}; do
  bspc rule -a $i desktop='^6' follow=on focus=on;
done

## Workspace 7 (Games)
declare -a games=(Snes9x-gtk)
for i in ${games[@]}; do
  bspc rule -a $i desktop='^7' follow=on focus=on;
done

## Workspace 8 (Settings)
declare -a settings=(Lxappearance Lxtask)
for i in ${settings[@]}; do
  bspc rule -a $i desktop='^8' follow=on focus=on;
done

## Floating windows
declare -a floats=(Alafloat feh Viewnior)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on;
done

# Kill if already running
killall -9 picom sxhkd dunst udiskie lxsession lxpolkit xfce4-power-manager

# Launch session manager
lxsession &

# Launch notification daemon
dunst -config $HOME/.config/dunst/dunstrc &

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Launch udiskie
udiskie &

# Launch compositor
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
