general.import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]
general.live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 12
y = 12

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"
