[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.normal]
black = "0x1f1f28"
red = "0xe46876"
green = "0x98bb6c"
yellow = "0xe6c384"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x7aa89f"
white = "0xdcd7ba"

[colors.bright]
black = "0x16161d"
red = "0xc34043"
green = "0x76946a"
yellow = "0xdca561"
blue = "0x658594"
magenta = "0x938aa9"
cyan = "0x6a9589"
white = "0xc8c093"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17
